/**
 * Canonical backend endpoint paths for the OfficeOS FastAPI API (/api/v1).
 */

export const API_ENDPOINTS = {
  health: "/health",
  me: {
    profile: "/me",
    organizations: "/me/organizations",
    permissions: "/me/permissions",
  },
  organizations: {
    list: "/organizations",
    detail: (id: string) => `/organizations/${id}`,
    members: (id: string) => `/organizations/${id}/members`,
    current: "/organizations/current",
    currentSettings: "/organizations/current/settings",
    currentBranches: "/organizations/current/branches",
    currentBranch: (id: string) => `/organizations/current/branches/${id}`,
    currentRoles: "/organizations/current/roles",
    currentMembers: "/organizations/current/members",
    currentMember: (id: string) => `/organizations/current/members/${id}`,
  },
  departments: {
    list: "/departments",
    detail: (id: string) => `/departments/${id}`,
  },
  employees: {
    list: "/employees",
    detail: (id: string) => `/employees/${id}`,
    managers: "/employees/managers",
  },
  attendance: {
    list: "/attendance",
    clockIn: "/attendance/clock-in",
    clockOut: "/attendance/clock-out",
  },
  leave: {
    types: "/leave-types",
    typeDetail: (id: string) => `/leave-types/${id}`,
    requests: "/leave-requests",
    requestDetail: (id: string) => `/leave-requests/${id}`,
    approve: (id: string) => `/leave-requests/${id}/approve`,
    reject: (id: string) => `/leave-requests/${id}/reject`,
    cancel: (id: string) => `/leave-requests/${id}/cancel`,
    summary: "/leave-requests/summary",
    holidays: "/holidays",
    holidayDetail: (id: string) => `/holidays/${id}`,
    list: "/leave-requests",
    balance: "/leave-requests/summary",
  },
  clients: {
    list: "/clients",
    create: "/clients",
    detail: (id: string) => `/clients/${id}`,
    update: (id: string) => `/clients/${id}`,
    delete: (id: string) => `/clients/${id}`,
    contacts: (clientId: string) => `/clients/${clientId}/contacts`,
    contactDetail: (clientId: string, contactId: string) => `/clients/${clientId}/contacts/${contactId}`,
  },
  projects: {
    list: "/projects",
    create: "/projects",
    detail: (id: string) => `/projects/${id}`,
    update: (id: string) => `/projects/${id}`,
    delete: (id: string) => `/projects/${id}`,
    members: (projectId: string) => `/projects/${projectId}/members`,
    memberDetail: (projectId: string, memberId: string) => `/projects/${projectId}/members/${memberId}`,
  },
  vendors: {
    list: "/vendors",
    create: "/vendors",
    detail: (id: string) => `/vendors/${id}`,
    update: (id: string) => `/vendors/${id}`,
  },
  purchaseRequests: {
    list: "/purchase-requests",
    create: "/purchase-requests",
    detail: (id: string) => `/purchase-requests/${id}`,
    update: (id: string) => `/purchase-requests/${id}`,
    submit: (id: string) => `/purchase-requests/${id}/submit`,
    approve: (id: string) => `/purchase-requests/${id}/approve`,
    reject: (id: string) => `/purchase-requests/${id}/reject`,
    cancel: (id: string) => `/purchase-requests/${id}/cancel`,
  },
  purchaseOrders: {
    list: "/purchase-orders",
    create: "/purchase-orders",
    detail: (id: string) => `/purchase-orders/${id}`,
    update: (id: string) => `/purchase-orders/${id}`,
    cancel: (id: string) => `/purchase-orders/${id}/cancel`,
    close: (id: string) => `/purchase-orders/${id}/close`,
  },
  assets: {
    list: "/assets",
    create: "/assets",
    detail: (id: string) => `/assets/${id}`,
    update: (id: string) => `/assets/${id}`,
    delete: (id: string) => `/assets/${id}`,
    assignments: (id: string) => `/assets/${id}/assignments`,
    assign: (id: string) => `/assets/${id}/assign`,
    return: (id: string) => `/assets/${id}/return`,
  },
  maintenanceRequests: {
    list: "/maintenance-requests",
    create: "/maintenance-requests",
    detail: (id: string) => `/maintenance-requests/${id}`,
    update: (id: string) => `/maintenance-requests/${id}`,
    approve: (id: string) => `/maintenance-requests/${id}/approve`,
    reject: (id: string) => `/maintenance-requests/${id}/reject`,
    schedule: (id: string) => `/maintenance-requests/${id}/schedule`,
    cancel: (id: string) => `/maintenance-requests/${id}/cancel`,
  },
  maintenanceRecords: {
    list: "/maintenance-records",
    create: "/maintenance-records",
    detail: (id: string) => `/maintenance-records/${id}`,
    update: (id: string) => `/maintenance-records/${id}`,
    start: (id: string) => `/maintenance-records/${id}/start`,
    complete: (id: string) => `/maintenance-records/${id}/complete`,
    cancel: (id: string) => `/maintenance-records/${id}/cancel`,
  },
  trainingPrograms: {
    list: "/training-programs",
    create: "/training-programs",
    detail: (id: string) => `/training-programs/${id}`,
    update: (id: string) => `/training-programs/${id}`,
    delete: (id: string) => `/training-programs/${id}`,
    publish: (id: string) => `/training-programs/${id}/publish`,
    cancel: (id: string) => `/training-programs/${id}/cancel`,
    complete: (id: string) => `/training-programs/${id}/complete`,
  },
  trainingSessions: {
    list: "/training-sessions",
    create: "/training-sessions",
    detail: (id: string) => `/training-sessions/${id}`,
    update: (id: string) => `/training-sessions/${id}`,
    delete: (id: string) => `/training-sessions/${id}`,
  },
  trainingEnrollments: {
    list: "/training-enrollments",
    create: "/training-enrollments",
    detail: (id: string) => `/training-enrollments/${id}`,
    update: (id: string) => `/training-enrollments/${id}`,
    attend: (id: string) => `/training-enrollments/${id}/attend`,
    complete: (id: string) => `/training-enrollments/${id}/complete`,
    cancel: (id: string) => `/training-enrollments/${id}/cancel`,
  },
  internships: {
    list: "/internships",
    create: "/internships",
    detail: (id: string) => `/internships/${id}`,
    update: (id: string) => `/internships/${id}`,
    delete: (id: string) => `/internships/${id}`,
    start: (id: string) => `/internships/${id}/start`,
    complete: (id: string) => `/internships/${id}/complete`,
    extend: (id: string) => `/internships/${id}/extend`,
    terminate: (id: string) => `/internships/${id}/terminate`,
    supervisors: (id: string) => `/internships/${id}/supervisors`,
    supervisor: (id: string, supId: string) => `/internships/${id}/supervisors/${supId}`,
    reviews: (id: string) => `/internships/${id}/reviews`,
    review: (id: string, reviewId: string) => `/internships/${id}/reviews/${reviewId}`,
  },
  operations: {
    tasks: "/operations/tasks",
    createTask: "/operations/tasks",
    taskDetail: (id: string) => `/operations/tasks/${id}`,
    updateTask: (id: string) => `/operations/tasks/${id}`,
    deleteTask: (id: string) => `/operations/tasks/${id}`,
    assignTask: (id: string) => `/operations/tasks/${id}/assign`,
    startTask: (id: string) => `/operations/tasks/${id}/start`,
    completeTask: (id: string) => `/operations/tasks/${id}/complete`,
    cancelTask: (id: string) => `/operations/tasks/${id}/cancel`,
    checklists: (taskId: string) => `/operations/tasks/${taskId}/checklist`,
    createChecklist: (taskId: string) => `/operations/tasks/${taskId}/checklist`,
    updateChecklist: (taskId: string, itemId: string) => `/operations/tasks/${taskId}/checklist/${itemId}`,
    deleteChecklist: (taskId: string, itemId: string) => `/operations/tasks/${taskId}/checklist/${itemId}`,
  },
  finance: {
    overview: "/finance/overview",
    categories: "/finance/expense-categories",
    createCategory: "/finance/expense-categories",
    categoryDetail: (id: string) => `/finance/expense-categories/${id}`,
    updateCategory: (id: string) => `/finance/expense-categories/${id}`,
    deleteCategory: (id: string) => `/finance/expense-categories/${id}`,
    expenses: "/finance/expenses",
    createExpense: "/finance/expenses",
    expenseDetail: (id: string) => `/finance/expenses/${id}`,
    updateExpense: (id: string) => `/finance/expenses/${id}`,
    submitExpense: (id: string) => `/finance/expenses/${id}/submit`,
    approveExpense: (id: string) => `/finance/expenses/${id}/approve`,
    rejectExpense: (id: string) => `/finance/expenses/${id}/reject`,
    payExpense: (id: string) => `/finance/expenses/${id}/pay`,
    cancelExpense: (id: string) => `/finance/expenses/${id}/cancel`,
    transactions: "/finance/transactions",
    createTransaction: "/finance/transactions",
    transactionDetail: (id: string) => `/finance/transactions/${id}`,
    updateTransaction: (id: string) => `/finance/transactions/${id}`,
  },
  documents: {
    list: "/documents",
    create: "/documents",
    detail: (id: string) => `/documents/${id}`,
    update: (id: string) => `/documents/${id}`,
    delete: (id: string) => `/documents/${id}`,
    versions: (id: string) => `/documents/${id}/versions`,
    createVersion: (id: string) => `/documents/${id}/versions`,
    versionDetail: (id: string, verId: string) => `/documents/${id}/versions/${verId}`,
    download: (id: string) => `/documents/${id}/download`,
    uploadUrl: "/documents/upload-url",
    permissions: (id: string) => `/documents/${id}/permissions`,
    createPermission: (id: string) => `/documents/${id}/permissions`,
    updatePermission: (id: string, permId: string) => `/documents/${id}/permissions/${permId}`,
    deletePermission: (id: string, permId: string) => `/documents/${id}/permissions/${permId}`,
  },
  notifications: {
    list: "/notifications",
    create: "/notifications",
    unreadCount: "/notifications/unread-count",
    detail: (id: string) => `/notifications/${id}`,
    markRead: (id: string) => `/notifications/${id}/read`,
    markUnread: (id: string) => `/notifications/${id}/unread`,
    markAllRead: "/notifications/mark-all-read",
    archive: (id: string) => `/notifications/${id}/archive`,
    preferences: "/notifications/preferences",
    updatePreferences: "/notifications/preferences",
  },
  auditLogs: {
    list: "/audit-logs",
    detail: (id: string) => `/audit-logs/${id}`,
  },
  settings: {
    general: "/settings/general",
  },
} as const;
